create table parts_requests (
    id bigint generated by default as identity primary key,
    part_number text,
    brand_name text,
    company_name text,
    contact_name text,
    contact_number text,
    part_price numeric,
    email_sent_to text,
    email_type text,
    created_at timestamptz not null default now()
);